### PR TITLE
Rounded corners on rectangle used as subsurface

### PR DESCRIPTION
**Pull request by Damov**
Capability to make corners round on rectangle which is used as subsurface:

- Added possibility to make corners on rectangle subsurface round

### CODE REVIEW

**Comment by ramcdona** [comment]
Damov,

Thanks for this change.

I had a few changes that I made on top of yours.  Please check them out and let me know what you think.

[RoundedRectSubSurf](https://github.com/ramcdona/OpenVSP/tree/RoundedRectSubSurf)

**Comment by Damov** [comment]
Hey,

looks fine to me. You can include it in the next version if you like.

Regards,
Daniel

**Comment by ramcdona** [comment]
Rather than a four-vertex poly, do you think it would be better to support an N-vert poly?

It would require arrays of parameters -- something that is done with CST airfoils and a couple other places.

**Comment by Damov** [comment]
Hey,

this is the next step. I am not so confident with the code yet. Still learning. But I have a lot of ideas.

I redone and finished yesterday a four vertex poly based on VspCurve for wind screen design (as an example). I will push it later. I think, in future we can extend the code by more complex subsurfaces based on that class. It will be very helpful as it will provide the possibility to define easily wind screens, windows, hatches. They play a significant role in mass estimation. 

However, here is still an issue with the pull down menu in FeaStructure window. It is selecting the control surface and not the four vertex poly. The same problem I had in ScreenBase.cpp, ln. 939.  There might be a potential issue in ScreenBase.cpp, ln. 939: As long as the enum is listing the subsurfaces in the correct way, this works. The menu is not returning the item index of the enum back. As long as I understood it is returning the index of the menu item?

Kind regards,
Daniel

**Comment by ramcdona** [comment]
Yes, the Choice GuiDevice returns the index of the menu item -- it doesn't
know anything about the enums.

We may have skipped some of the subsurface types for structures -- the
easiest fix may be to make sure they are all represented everywhere.

Rob

**Comment by Damov** [comment]
I see, okay. Will let you know then once I finished the work. Happy new year!

**Pull request closed without merging**
