### PR TITLE
Make OpenVSP compile on FreeBSD (32 and 64 bits)

### PR DESCRIPTION
**Pull request by fernape**
Hi,

I'm the porter and maintainer of OpenVSP for FreeBSD. I made some changes so it can build cleanly on FreeBSD 32 and 64 bits. Changes are splitted in 4 pieces:
- Add -fPIC for .a objects when they are meant to be part of a .so object
- Add missing include files
- Fix case for include files
- Add some search paths for include files

### CODE REVIEW

**Comment by ramcdona** [comment]
Do you think adding -fPIC all over is the best way to solve that issue?  Would setting CMAKE_POSITION_INDEPENDENT_CODE solve the problem for you instead?

Likewise, I'm not a big fan of directly adding /usr/local/include to the CMake files.  That seems like something that CMake or the compiler should be able to figure out automatically.  Is there something in particular that you were trying to address with this?

I really appreciate your efforts to make OpenVSP easy to get and use for people on FreeBSD.

I don't check GitHub very often for things like this -- I check the Google Group much more frequently.

**Comment by ramcdona** [comment]
On a similar note, perhaps another cleaner fix would be to fix the conditional in src/CMakeLists.txt (line 15) that isn't triggering...

IF(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
ENDIF()

**Comment by fernape** [comment]
Hi there!

Thanks for taking the time for reviewing the patch. Here are my thoughts:

* You're right, adding the conditional is better. I fixed it adding "amd64" since that is proper value in FreeBSD. I also added the conditional to the SuperProject CMakeLists.txt since some of the libraries need the -fPIC flag.

* We need to add /usr/local/include in some cases so vsp is able to find thirdparty software on FreeBSD.

Do you want me to come with a new patch?

**Comment by ramcdona** [comment]
Does FreeBSD have CMake 2.8.9 or newer?  That appears to be the version that introduces CMAKE_POSITION_INDEPENDENT_CODE.  I believe getting rid of the conditional and setting that variable will let CMake take care of this isue for us in the most elegant way.

What specific third party software do you need to manually include /user/local/include for?  Anything we rely on should be specified through the various include variables in CMake.

No new patch at this time.

**Comment by fernape** [comment]
Sure, I'm using CMake 3.5.0.

I build tested with CMAKE_POSITION_INDEPENDENT_CODE. This will add -fPIC unconditionally. For 32 bit platform -fPIC is not necessary and it will have a performance impact (more about that [here](https://wiki.gentoo.org/wiki/Project:AMD64/Fixing_-fPIC_Errors_Guide)). So I think it's better to keep the conditional and make the code run as fast as possible in 32 bit.

All third party software (everything that is not in the base system) is installed under /usr/local. This applies for desktop environments, libraries, programs, etc. As a common rule, we try not to use bundled software if FreeBSD ports can provide the same libraries. In this case, we compile OpenVSP with parameters as:

`-DVSP_USE_SYSTEM_LIBXML2:BOOLEAN=yes
-DVSP_USE_SYSTEM_FLTK:boolean=yes
...`

In order to enable CMake to find these libraries we need to include /usr/local in the search paths.

**Comment by ramcdona** [comment]
Ok, then I think the best solution will be to put CMAKE_POSITION_INDEPENDENT_CODE inside the 64-bit conditional.

I'm great with you using VSP_USE_SYSTEM_XXXX -- that is exactly what it is for.  However, the hope and expectation is that the calls to FIND_PACKAGE(XXXX REQUIRED) in src/external/CMakeLists.txt will take care of finding those libraries and setting appropriate INCLUDE _DIR variables and whatnot.

Is one of those FIND_PACKAGE calls not working?  In that case, the best fix would be to pass additional search path hints to that FIND_PACKAGE call.

**Comment by fernape** [comment]
* OK. I keep the conditional.

* Several of them are not working (cpptest, fltk...). Should I add the path to `CMAKE_MODULE_PATH` instead of the particular FIND_PACKAGE calls?

**Comment by ramcdona** [comment]
Usually, there is a variable you can set before the call to FIND_PACKAGE that will help that module do its job.  You shouldn't have to modify the module.

In cases where we have no choice, we end up carrying our own FindXXX.cmake script in src/cmake.  Unfortunately, there are a bunch of these already.

cpptest is one that we already carry a Find macro of our own.  So, in that case, the best fix is to modify that so it can find what it needs on your platform.

FLTK's CMake integration is a bit of a mess (it often won't find Fluid), and they're in a major state of flux before the next major release 1.4.0 -- so I don't see things getting better.  That said, I think you can set  FLTK_INCLUDE_SEARCH_PATH before the FIND_PACKAGE( FLTK ) call.

**Comment by fernape** [comment]
I managed to inject /usr/local from our ports infrastructure via CMAKE_PREFIX_PATH so no changes to vsp are necessary for that matter.

In a few days I can come up with a new patch that would consist on the following:
* Adding missing includes
* Fixing case sensitiveness for include files
* Add -fPIC conditionally for amd64 platform

Does it sound good?

**Comment by ramcdona** [comment]
I'm working on a 'Next Release' locally on my machine.

I've already fixed the case sensitivity issue.  I've also cherry-picked your missing includes fix.

I am happy to update the PIC conditional -- if you can confirm which CMAKE variable I should test against on your platform.

**Comment by fernape** [comment]
I updated the pull request just in case. On FreeBSD the proper value for `CMAKE_SYSTEM_PROCESSOR` is  "amd64" ([commit](https://github.com/fernape/OpenVSP/commit/02ef6dd2220a8706c95f10776367f5f3c0a33547))

**Comment by ramcdona** [comment]
Thanks, I'll make sure that is in the next release.

If you have FreeBSD packaging files that you would like to carry in the OpenVSP source tree, I am happy to accept those.  I would love to have some Linux packages, but so far nobody with the expertise has come forward.

**Comment by fernape** [comment]
Terriffic.

The packaging code is specific of the ports infrastructure and is based on our makefile's hierarchy and libraries.

You can have a look here:
https://www.freshports.com/cad/openvsp

**Comment by ramcdona** [comment]
Thanks, I will check out.

BTW, freshports.com takes me someplace sketchy.  I think you meant .org.

**Comment by fernape** [comment]
Sorry about that. I wrote from (faulty) memory ;)

**Comment by fernape** [comment]
Hi again,

I just discover we need one more patch:

--- Libraries/cmake/External_CMinpack.cmake.orig        2016-02-14 00:01:30 UTC
+++ Libraries/cmake/External_CMinpack.cmake
@@ -1,3 +1,6 @@
+SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lm -fPIC")
+SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -lm -fPIC")
+
 ExternalProject_Add( CMINPACK
     URL ${CMAKE_CURRENT_SOURCE_DIR}/cminpack-1.3.3.tar.gz
     CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
@@ -8,4 +11,4 @@ ExternalProject_Add( CMINPACK
         -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
 )
 ExternalProject_Get_Property( CMINPACK BINARY_DIR INSTALL_DIR )
-SET( CMINPACK_INSTALL_DIR ${INSTALL_DIR} )
\ No newline at end of file
+SET( CMINPACK_INSTALL_DIR ${INSTALL_DIR} )

This patch adds -lm to the linking options of cminpack. Otherwise it complains about not finding sqrt().

Thanks!

**Comment by ramcdona** [comment]
I would prefer to fix this 1) in a way that only changes FreeBSD and 2) in the upstream project itself.

CMinpack appears to be active - and on GitHub.  We can make the changes to their build system, and then incorporate that version in OpenVSP -- hopefully the project will incorporate our changes down the road. 

Their build system already has logic for -fPIC, but it doesn't capture FreeBSD.

Why does FreeBSD need -lm when other platforms are able to grab it implicitly?  I also don't think that adding -lm to the compiler flags is the best way to handle this in CMake.

**Comment by fernape** [comment]
I agree. I will send a pull request for cminpack and hope they accept it.

About the other thing, I would ask instead _why are other systems grabbing -lm implicitly?_ That is not nominal behavior.

**Comment by ramcdona** [comment]
Even if cminpack doesn't take your patches upstream, if they look reasonable, OpenVSP can include the version of cminpack with the patches.

It looks like linking to the math library is more complex than you might first imagine...
https://cmake.org/Wiki/CMake_2.6_Notes#Linking_to_System_Libraries

I'm not sure what the right solution is, but unconditionally forcing it as a CFLAGS on all platforms, for compile and link, is clearly not a good solution.

**Comment by fernape** [comment]
I suppose there's something specific about how CMake behaves in FreeBSD. Our math library is in /usr/lib directory too so that shouldn't make any difference.

Anyway, I'll come up with a patch for cminpack considering FreeBSD in the relevant parts of their CMakeLists.txt and send them a pull request.

Cheers.

**Comment by fernape** [comment]
[Done](https://github.com/devernay/cminpack/pull/6)

**Pull request closed without merging**
