### PR TITLE
Fix include caseness

### PR DESCRIPTION
**Pull request by fernape**
There are some caseness issues in the include directives. Some of these are already present in want-to-be-merged pull requests...

Please, commit this. This one fixes building on FreeBSD, Linux, etc.

### CODE REVIEW

**Comment by ramcdona** [comment]
Would you mind rebasing the changes you need on top of 3.13.0?  I find it difficult to see what changes you're actually submitting when so many of the changes are Merges.

I actually checked your branch this morning and wasn't able to pick out any differences.  Now I see the latest case changes -- but is that it?  Am I missing something?

**Comment by fernape** [comment]
Sure thing. [Here](https://github.com/OpenVSP/OpenVSP/pull/81).

I track the upstream project from time to time but usually I don't need any changes (besides the ones we already apply on FreeBSD) and I test the release once it is out.

If you have a look [here](https://svnweb.freebsd.org/ports/head/cad/openvsp/files/), you can see the patches we need to apply in order to build OpenVSP in FreeBSD. The main goal is to push as many patches as we can to the upstream projects so they can be integrated if possible.

**Comment by ramcdona** [comment]
Thanks for clearing that up -- it confirms what I thought -- I was mostly caught up with your stuff.  Sorry for not catching the case problem.  That happens all too often.

Your FreeBSD changes look pretty harmless.  If you put together a branch, I can probably pull them in.

I try not to pull in platform-specific hard-code tweaks of the build files, but I don't think that these changes fit that description.

**Comment by ramcdona** [comment]
3.13.0 should be cleanest.  Thanks much.

**Pull request closed without merging**
