### PR TITLE
Added mouse wheel zoom to main window

### PR DESCRIPTION
**Pull request by iforce2d**

### CODE REVIEW

**Comment by ramcdona** [comment]
Looks like you're having a lot of fun with the models.

I've often thought about things that could be done in OpenVSP to support model building -- whether 3D printing, carved foam, or balsa buildup.

I doubt I'll ever have time to pursue those kinds of things, but if some modelers who could code implemented features like that, I would certainly be happy to include them.

**Comment by ramcdona** [comment]
Implemented in different way, included in 3.26.  Thanks for doing this.

**Comment by iforce2d** [comment]
I just tried 3.31.1 (build from latest source on Fedora 36) and the mouse wheel still does nothing. Do I need to enable a setting somewhere?

**Comment by ramcdona** [comment]
No, it should 'just work'.  

It could be that Fedora is not passing the scroll event through as it is expected.  That would most likely be an issue with the version of FLTK that is packaged with Fedora.  Can you figure out what FLTK they're using?

**Comment by iforce2d** [comment]
Looks like this line where the scroll increment is multiplied by 0.5 is the problem. On my Linux at least, the scroll wheel reports values of 1 or -1 depending on the scroll direction. So this becomes 0.5, and when passed to Display::zoom( int, int ) it will be zero.

Selection_1080

So I was able get the mousewheel zoom working by just removing the 0.5 scaling. However, having now seen the result I don't think this zoom behavior is what people were wanting. It only zooms without altering the view position, which we could already do by holding middle mouse button and moving the mouse up/down. The real advantage of mousewheel zoom is that you can zoom into a specific point, as demonstrated in my video. So it also functions as pan quite well, in fact most of the time I no longer need to actually click any buttons for pan/zoom navigation.
https://youtu.be/GCSre6XGqL8

**Comment by ramcdona** [comment]
Thanks for that video, I hadn't noticed the subtle nature of the difference.

More recent versions of FLTK (than are installed with most Linux distributions) have changed the arguments to these kinds of functions from integer to floating point for exactly this kind of reason.

I will go back and look at your original patches and see what it takes to implement the scroll zoom the way you had imagined it.

**Comment by ramcdona** [comment]
Thanks for bringing it up.  A version of this will go into the next release.  It needed a small adjustment to work on high-resolution displays.  I.e. where the graphics system works in a coordinate system that is not 1:1 with hardware pixels.

**Pull request closed without merging**
