### PR TITLE
Upgraded CMake build process to enable specification of Python version to pass to environment.yml

### PR DESCRIPTION
**Pull request by jrwelstead**
Based off of OpenVSP 3.29.1.  Unable to build OpenVSP 3.30.0.

### CODE REVIEW

**Comment by ramcdona** [comment]
I do not think the Ubuntu build currently honors the build matrix Python version.  Instead, I think it defaults to the Python installed with the Ubuntu distribution (at least that is my intent).

Consequently, I do not think we should pass the VSP_PYTHON_VERSION_NUM to the CMake command for the Ubuntu build.  Further, it would be ideal to instead have CMake figure out the version of python found on the machine and set the variable that goes to the environment.yml.in appropriately.

I also do not understand the desire in the first commit to pass the build type as a variable -- do you intend to use the GitHub build to make a debug build?  I suppose it is harmless, but true debug builds of OpenVSP are generally too slow to be of any use.  I use ReleaseWithDebugInfo regularly, but to my knowledge, you will still need a full development environment set up in order to run the debugger on the result -- and so you might as well compile locally.

To be honest, I had never noticed that there was a BUILD_TYPE variable in the build.yml file.  If it is not required by GitHub (perhaps it is) I would suggest that removing the BUILD_TYPE variable may be a simpler solution to the mismatch between what we pass to CMake and this variable setting.

**Comment by jrwelstead** [comment]
This was simply an attempt to have the Python version specified in
environment.yml to match the two versions of Python you are building.
Right now, your distributions (3.6 and 3.9) are both hard coded to v3.6 in
the environment.yml files.  If a user downloads the Python 3.9 version and
follows the setup instructions it will not work due to the version
mismatch.  The idea was to have the environment.yml always match the
versions of Python in your build matrix.  I did not envision this getting
used anywhere except in the Github build process.

Given that my intent was only to use this as part of the build process for
the distribution versions (aka, download from the website), it didn't
matter to me to try and match what cmake detects.  B/c the build process
sets up the environment, the versions of Python will ALWAYS be consistent.
It could be expanded to parse the string, but I was trying to keep it
simple.

Not a desire to pass the build type as a variable.  I simply noticed in
most places it was $BUILD_TYPE but in others it was Release.  I simply
thought it was an unintended inconsistency and was making it all the same.

Jason

**Comment by ramcdona** [comment]
Thanks for your work on this.  I've taken a somewhat different approach, but I think it'll give the same result.

And of course I rebased and then modified on my local machine (rather than merge through this interface).  So I'm closing this manually.

I'm hoping to push out the new version before 10/31, so it should be soon.

**Comment by jrwelstead** [comment]
No problem.  I simply made an attempt to reach a desired end state.  If
there is a better way to do it, then that's great.

Thanks,
Jason

**Comment by ramcdona** [comment]
Let me know if it has trouble, I should have inspected all the 3.31.0 *.zip
files produced -- but I didn't...

Rob

**Pull request closed without merging**
